### PR TITLE
SSL/TLS Handshake Visualization GUI improvements in regard to #117 

### PR DESCRIPTION
**Pull request by tforneberg**
Solution to  #117. 
Many GUI parts of this plug-in were using the AbsoluteLayout. This caused problems with High-DPI monitors (cropped text etc.). 
I converted a big part of these into the GridLayout and optimized the overall layout a little bit. 
- There is no more cropped text even at High-DPI monitors
- The navigation buttons on the bottom are moved below the information text area, since most of the time there is not much text to display and it was a waste of space. 
- The information text area is responsive to the overall window size and gets a scroll bar below a certain overall window width. 

Before: 
ssl_tls_handshake__before

After: 
ssl_tls_handshake_after

### CODE REVIEW

**Comment by be4** [comment]
Great job -- thanks.

- Could you add a short description area under the title.
I guess the visualizations should consistently have the structure/layout
of Title --> Description --> Real visualization.

- Broaden the left column a bit that AES_256_GCM_SHA384 is not truncated;
   same with the right col because of TLS_DHE_RSA_WITH_AES

- Why is there a mix of German and English?
   - Version, Server, Client, Cipher Suite, Session ID seems ok to me.
      Also other things from the RFC.
   - However, I guess, Finished and Random could be translated to German.
   - I also recommend to name the right frame "Erklärung" instead of
"Information"
   

Best regards, Bernhard


Am 25.10.2017 um 16:32 schrieb Tobias Forneberg:
> Solution to  #117. 
> Many GUI parts of this plug-in were using the AbsoluteLayout. This caused problems with High-DPI monitors (cropped text etc.). 
> I converted a big part of these into the GridLayout and optimized the overall layout a little bit. 
> - There is no more cropped text even at High-DPI monitors
> - The navigation buttons on the bottom are moved below the information text area, since most of the time there is not much text to display and it was a waste of space. 
> - The information text area is responsive to the overall window size and gets a scroll bar below a certain overall window width. 
>
> Before: 
> ssl_tls_handshake__before
>
> After: 
> ssl_tls_handshake_after
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jcryptool/crypto/pull/125
>
> -- Commit Summary --
>
>   * Test commit
>   * GUI Improvement of the plugin (AbsoluteLayout -> GridLayout).
>   * Undo test commit
>   * Further GUI improvement/bug fixing
>
> -- File Changes --
>
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ClientCertificateComposite.java (47)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ClientChangeCipherSpecComposite.java (20)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ClientFinishedComposite.java (13)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ClientHelloComposite.java (102)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ServerCertificateComposite.java (87)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ServerChangeCipherSpecComposite.java (24)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ServerFinishedComposite.java (10)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/ServerHelloComposite.java (120)
>     M org.jcryptool.visual.ssl/src/org/jcryptool/visual/ssl/views/SslView.java (98)
>
> -- Patch Links --
>
> https://github.com/jcryptool/crypto/pull/125.patch
> https://github.com/jcryptool/crypto/pull/125.diff
>

**Comment by simlei** [comment]
Nice pull request formatting!

when done with the changes @be4 suggested, just update the pull request. This is simply done by adding commits to your PR branch and pushing it again; the PR here will be updated automatically. (in case you didn't know already)

**Comment by simlei** [comment]
I have merged it accidentally already - got the wrong tab. Please submit followup changes in a new PR. Thanks & sorry for the mixup.

**Comment by tforneberg** [comment]
Thanks! No problem! I will do the suggested changes the next days and open a new PR.

**Pull request merged**
