### PR TITLE
GUI and Usability fixes in ElGamal

### PR DESCRIPTION
**Pull request by grthor**
Commmit b60d5cc : 
Removed help icons from all dialog pages where no help was available.
help_icons
no_help_icons
minor changes to the user interface. Such as text boxes, which now use the full width.
textfields_cropped
textfields_full_width

### CODE REVIEW

**Comment by grthor** [comment]
Commit 9663416 : 
With "key selection" -> "existing public key" a key is automatically selected.
key_autoselection

**Comment by grthor** [comment]
Commit 7880a32 
Only little things (Typos and highHints removed).

**Comment by grthor** [comment]
Commit bfa00f3
Added three buttons to "key selection" -> "manual input" Dialog. If a value has already been entered, a value near it will be suggested. If no value has been entered yet, a value will be chosen randomly.
old_public_key_parameters
new_public_key_parameters

**Comment by grthor** [comment]
Commit e343c96 
Textfields in the Save Keypair Dialog ow use the full width.
old_key_owner
new_key_owner
Removed reused GridData and useless spacer labels.

**Comment by grthor** [comment]
Commit 495e721 
A key is directly selected when the Load Keypair Dialog opens. The sentence "if no password is set ... " is removed because it does not work without a password.
old_load_keypair
new_load_keypair

**Comment by grthor** [comment]
Commit 7783d9a 
Removed about 30 Typos and some text changes

**Comment by grthor** [comment]
Commit 534dba6 
The layout of the dialogues unified. Left and right are left 50 pixels distance to the edge.
dialog_margin

**Comment by grthor** [comment]
Commit 021f492
Take over data from "Encrypt" to "Decrypt" works now.

**Comment by grthor** [comment]
Commit 346262c
The Buttons on the left side of the plugin are now on the same height as the corresponding groups on the right.
old_main_layout
new_main_layout

**Comment by simlei** [comment]
Please just leave a not when this branch is ready to be merged :) looks very nice btw

**Comment by grthor** [comment]
The newPublicKey dialog page now likes like this. 
grafik
Separator and additional free space visually separate the different parameters. I used separators so that the Layout of the dialog is consistent with the other dialogs. In addition, a few colons have been added.

The dialog under "Sign" -> "Select parameters" now also has the uniform layout (50 pixel space left and right). The parameter P is now displayed so that it is directly visible to a user.
grafik

Under "Encrypt" in the result, a space has been displayed at the beginning. This resulted in a NullPointerException under "Decrypt". Unfortunately, in Decrypt now, the first letter appears twice because the NullPointerException was ignored in the code. Example: Hallo -> fab2 8399 1780b 1780b 9ea5 -> HHallo.
grafik
grafik

**Comment by simlei** [comment]
ready to merge?

**Comment by grthor** [comment]
No, there are still bugs that need to be fixed. In particular, the faulty decryption.

**Pull request merged**
