### PR TITLE
Added Online Help and Context Help for Substitution Analysis Plugin

### PR DESCRIPTION
**Pull request by CharlotteMagister**
I added the online- and context-help for the Substitution Analysis plugin.

Before:

German_Before

After:

English_After
German_After

### CODE REVIEW

**Comment by grthor** [comment]
Hi @CharlotteMagister looks good 👍 

Can you change the size of the imges in the online help to a relative value? You can do this with this code:
 ```<p align=center></p>```

Thank you in advance.

**Comment by CharlotteMagister** [comment]
@grthor Thanks for the example code. Fixed it. :)

**Comment by grthor** [comment]
Great :+1:

I will merge it now.

**Comment by CharlotteMagister** [comment]
@grthor Thank you!

**Pull request merged**
