### PR TITLE
Diffie Hellman 

### PR DESCRIPTION
**Pull request by grthor**

### CODE REVIEW

**Comment by grthor** [comment]
I changed the layout from FormLayout to GridLayout. The sizes of the individual buttons now adapts to the font size / window size. So no text is cut off anymore. Furthermore, the arrows from Group Bob to Alice and vice versa adapt to the size of the groups.
dh_bug
dh_1pdf
There are now two buttons with which you can turn off the annoying pop-ups and the animation after step 5 (Exchange shared keys).
In the Set public Parameters dialog, I changed the position of the Choose random curve button to the top right to make it consistent with the other other curve sizes and curve types.
dh_publicparameters_bug
dh_publicparamers_new
In all dialogues, I removed the help icons at the bottom left, because there was no help.
In the dialogues in which you enter the secrets of Bob and Alice, I've improved the verification of user input, so that you can no longer enter zero or negative values (which leads to problems). If you do it anyway, a hint is displayed that you have to enter another value.
dh_secret

**Comment by grthor** [comment]
The order of G is shown in brackets behind it. Since the order is relatively high, she pulls the window apart. Does not look so good.
alics_secret_fix

The key is now over the arrows between Bob and Alice. Since I can not come up with a better solution. Maybe hide the arrows so that only the key is displayed?
key_new

**Comment by grthor** [comment]
The groups Alice and Bob do not resize when opening / closing other windows.
groups_fix

**Comment by simlei** [comment]
are these the last changes?

**Comment by grthor** [comment]
No, there are more changes coming.

**Comment by grthor** [comment]
In the "select public parameter" dialog, G changes when you change the curve size from large to small. This fixes all bugs from #33 . 
The layout is unified in "select public parameters" dialog.
In the text field "elliptic curve" missing blanks were inserted. <sup> and </ sup> were removed.
ecdh_final

The order of G is displayed above the input field for the secret when a large curve size has been selected.
ecdh_selectsecret

Multiple used GridData has been removed.

**Pull request merged**
